### ISSUE TITLE
popup页面宽度太小了，带翻译框输入很小，要是能设置宽度就好了

### ISSUE THREAD

**Issue by hejin06** [chunibyocola/sc-translator-crx#102]
![搜狗截图20221211235756](https://user-images.githubusercontent.com/120325309/206914263-ff15b1b8-668b-4a00-bc42-ac5e2101f31c.png) 当有长文本时候就容易分行，阅读就很不直观，不方便，也不够大气。

**Comment by chunibyocola** [comment]
可以使用自定义样式功能来设置，比如复制下方代码：
```CSS
.popup-container { width: 350px; }
```
到自定义样式输入框里，然后点击保存，打开 popup 页面就可以看到宽度被设置为 350px，你也可以把 350 换成其他数字。
