### ISSUE TITLE
Option to hide the translation box

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#121]
When using inline translation pasting the result into the webpage, I'd like to be able to not open the translation window at all.

**Comment by chunibyocola** [comment]
I am not clearly get what your are meaning, do you mean that you are using "automatically insert result into webpage" and you don't want the translation panel show up, right?

If so, there is a roundabout way that you can enable "Remember the position of the pinned panel" and place the panel somewhere you won't notice.

Or you can try to make it works through CSS customizaion "Customize style".

**Comment by mrsimpson** [comment]
> "automatically insert result into webpage" and you don't want the translation panel show up, right?

Exactly. I also took your workaround but still the popup appears – and I notice it no matter where ;)

**Comment by chunibyocola** [comment]
Copy the code below into CSS customizaion box, and this will help not see the panel:
```CSS
#sc-translator-root > .panel {
 display: none !important;
}
```

**Comment by mrsimpson** [comment]
I knew I could do that (in fact I already did), but then it never appears. Sometimes, I like to see it though without always needing to adapt the CSS.
How about adding the mode in which the translation happened to the css to `panel`?

Then I could statically do something like
```css
#sc-translator-root.dom-insert-translation > .panel {
 display: none !important;
}
```
