### ISSUE TITLE
希望简化下网页翻译步骤

### ISSUE THREAD

**Issue by YuI2333** [chunibyocola/sc-translator-crx#22]
1. 每次网页翻译都要点击右键网页翻译，然后点击翻译，然后点击切换译文，感觉太过繁琐了，
希望能提供设置选项，右键点击后能直接翻译，以及隐藏右下角的控制栏的选项。

2. 关于独立窗口，如图，这个控制栏希望能去掉，LOGO和上方冲突，皮肤和设置按钮没必要在这添加入口，希望您考虑下，万分感谢！
![32_44](https://user-images.githubusercontent.com/26202875/130170202-fa34684b-b44f-455e-bbb7-72e9db030671.png)

**Comment by chunibyocola** [comment]
你好。

关于 1：除了右键还可以选择使用快捷键。不过操作确实比较繁琐了。
我可以在选项页里增加一个“网页翻译”栏目，栏目里面有“译文展示方式”，“目标语言”，“源”这三个选择框以及一个“直接翻译（通过右键菜单或快捷键激活“网页翻译”后会直接进行翻译，同时也不会展示右下角的控制栏。但缺点是不可以切换语言、源、展示方式。想要关闭的话需要再次使用右键菜单或快捷键。）”选项。
其中“直接翻译”里的不展示右下角的控制栏大概会再拆分一个“不展示右下角控制栏”的选项，我目前也更倾向于这种做法。

关于 2：这个考虑到可能会有人需要，因此不直接硬删除。但你可以通过“自定义 CSS”来去掉他。复制下面这段 CSS 然后粘贴到“自定义样式”框里即可。
```CSS
.separate-container {
  padding-top: 5px;
}
.separate-container .popup-header {
  display: none;
}
```

谢谢你的反馈！
